{% set version = "1.3.7" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: lkml
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lkml/lkml-{{ version }}.tar.gz
  sha256: 51dc9f1b7e74cd7a00e0dbbf06fb573952015328f1f4a3a0730d444444a8ae7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - lkml = lkml.__init__:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
    - setup.cfg
  imports:
    - lkml
  commands:
    - pip check
    - lkml --help
    - coverage run --source=lkml --branch -m pytest -vv --tb=long --color=yes -k "not (absence_of_debug_flag_is_parsed_to_log_level_warn or block_with_multiple_quoted_fields or block_with_nested_block or block_with_single_quoted_field or debug_flag_is_parsed_to_log_level_debug or duplicate_non_top_level_keys or duplicate_top_level_keys
      or lists_with_comma_configurations or model_with_all_fields or reserved_dimension_names or view_with_all_fields)"
    - coverage report --show-missing --skip-covered --fail-under=89
  requires:
    - coverage
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/joshtemple/lkml
  summary: A speedy LookML parser implemented in pure Python.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://lkml.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
